# Generated by Django 4.1.3 on 2022-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
