# Generated by Django 4.1.3 on 2022-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(related_name='products', to='products.productimage'),
        ),
    ]
