# Generated by Django 4.1.3 on 2022-11-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
    ]
