# Generated by Django 4.1.3 on 2022-11-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_name_product_thumb_nail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumb_nail',
        ),
    ]
