# Generated by Django 4.1.3 on 2022-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_thumb_nail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb_nail',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images'),
            preserve_default=False,
        ),
    ]
